# docker-compose.yml
version: "3.9"
services:
db:
image: postgres:16-alpine
environment:
POSTGRES_USER: verdant
POSTGRES_PASSWORD: verdant
POSTGRES_DB: verdant
ports: ["5432:5432"]
volumes:
- db_data:/var/lib/postgresql/data
api:
build: ./api
depends_on: [db]
environment:
DATABASE_URL: postgres://verdant:verdant@db:5432/verdant
API_PORT: 8080
NODE_ENV: development
ports: ["8080:8080"]
web:
build: ./web
environment:
NEXT_PUBLIC_API_BASE: http://localhost:8080
ports: ["3000:3000"]
depends_on: [api]
volumes:
db_data:
