version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: verdantops
      POSTGRES_PASSWORD: verdantops
      POSTGRES_DB: verdantops
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on: [db]
    environment:
      VERDANTOPS_DB_URL: postgres://verdantops:verdantops@db:5432/verdantops
      VERDANTOPS_INGEST_TOKEN: ${VERDANTOPS_INGEST_TOKEN}
      CARBON_DEFAULT_GRID_INTENSITY_G_PER_KWH: ${CARBON_DEFAULT_GRID_INTENSITY_G_PER_KWH}
      CARBON_BUDGET_KG_PER_RUN: ${CARBON_BUDGET_KG_PER_RUN}
      PORT: 8080
    ports: ["8080:8080"]

  web:
    build: ./web
    depends_on: [api]
    environment:
      NEXT_PUBLIC_API_BASE: http://api:8080
    ports: ["3000:3000"]

volumes:
  dbdata:
